apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/instance: azure-mcp-server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: azure-mcp-server
    app.kubernetes.io/version: {{ .Values.app.version }}
  annotations:
    version: {{ .Values.app.version }}
spec:
  progressDeadlineSeconds: {{ .Values.spec.progressDeadlineSeconds }}
  replicas: {{ .Values.spec.replicas }}
  revisionHistoryLimit: {{ .Values.spec.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      app.kubernetes.io/instance: azure-mcp-server
      app.kubernetes.io/name: azure-mcp-server
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.spec.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.spec.strategy.rollingUpdate.maxUnavailable }}
    type: {{ .Values.spec.strategy.type }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        app.kubernetes.io/instance: azure-mcp-server
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: azure-mcp-server
        app.kubernetes.io/version: {{ .Values.app.version }}
      annotations:
        version: {{ .Values.app.version }}
        kubectl.kubernetes.io/default-container: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.spec.pod.serviceAccountName }}
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.spec.pod.containers.imageName }}
        command: [ "sh", "-c", "dotnet azmcp.dll server start --port 5008 --transport sse && tail -f /dev/null" ]
        imagePullPolicy: {{ .Values.spec.pod.containers.imagePullPolicy }}
        resources:
          limits:
            memory: {{ .Values.spec.pod.containers.resources.memory }}
          requests:
            cpu: {{ .Values.spec.pod.containers.resources.cpu }}
            memory: {{ .Values.spec.pod.containers.resources.memory }}
        ports:
        - name: {{ .Values.spec.pod.containers.ports.name }}
          containerPort: {{ .Values.spec.pod.containers.ports.containerPort }}
        env:
        - name: LOG_LEVEL
          value: {{ .Values.envVariables.logLevel }}
        - name: ENV_NAME
          value: {{ .Values.envVariables.envName }}
        - name: AZURE_TENANT_ID
          value: {{ .Values.envVariables.azureTenantId }}
        - name: AZURE_CLIENT_ID
          value: {{ .Values.envVariables.azureClientId }}
        - name: AZURE_CLIENT_SECRET
          value: {{ .Values.envVariables.azureClientSecret }}  
        livenessProbe:       
        readinessProbe:
        volumeMounts: 
      volumes: 
      restartPolicy: {{ .Values.spec.pod.restartPolicy }}
