labels:
  app: weather-mcp-server
  version: 1.0.0

namespace: 

app:
  version: 1.0.0

service:
  port: 8001

spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 120
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  pod:
    containers:
      imageName: 
      imagePullPolicy: IfNotPresent
      ports:
        containerPort: 8001
        name: http
      resources:
        memory: 1Gi
        cpu: 250m
    restartPolicy: Always

#Application environment variables
envVariables:
#  logLevel: INFO